name: amdari
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - aiohttp=3.9.0
  - aiosignal=1.2.0
  - altair=5.0.1
  - arrow-cpp=11.0.0
  - asttokens=2.0.5
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - blinker=1.6.2
  - boost-cpp=1.82.0
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.2
  - cryptography=41.0.7
  - datasets=2.12.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - dill=0.3.6
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.5.0
  - faiss-cpu=1.7.4
  - filelock=3.13.1
  - fontconfig=2.14.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2023.10.0
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.37
  - glib=2.69.1
  - glog=0.5.0
  - gmpy2=2.1.2
  - grpc-cpp=1.48.2
  - huggingface_hub=0.17.3
  - icc_rt=2022.1.0
  - idna=3.4
  - importlib-metadata=6.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.20.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyterlab_widgets=3.0.9
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.5.0
  - libdeflate=1.17
  - libevent=2.1.12
  - libfaiss=1.7.4
  - libffi=3.4.4
  - libiconv=1.16
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.14
  - networkx=3.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nltk=3.8.1
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.4.0
  - openssl=3.0.12
  - orc=1.7.4
  - pandas=2.1.4
  - parso=0.8.3
  - pcre=8.45
  - pdf2image=1.17.0
  - pillow=9.4.0
  - pip=23.3.1
  - pixman=0.40.0
  - platformdirs=3.10.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=3.20.3
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycparser=2.21
  - pydeck=0.8.1b0
  - pygments=2.15.1
  - pympler=0.9
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - pytesseract=0.3.13
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - pytorch=2.1.0
  - pytz=2023.3.post1
  - pywin32=305
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - re2=2022.04.01
  - referencing=0.30.2
  - regex=2023.10.3
  - requests=2.31.0
  - responses=0.13.3
  - rich=13.3.5
  - rpds-py=0.10.6
  - safetensors=0.4.0
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - sentence-transformers=2.2.2
  - sentencepiece=0.1.99
  - setuptools=68.2.2
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.1.10
  - sqlite=3.41.2
  - stack_data=0.2.0
  - streamlit=1.30.0
  - sympy=1.12
  - tbb=2021.8.0
  - tenacity=8.2.2
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tokenizers=0.13.3
  - toml=0.10.2
  - toolz=0.12.0
  - torchvision=0.15.2
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - transformers=4.32.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023d
  - tzlocal=2.1
  - urllib3=1.26.18
  - utf8proc=2.6.1
  - validators=0.18.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - win_inet_pton=1.1.0
  - xxhash=0.8.0
  - xz=5.4.5
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - annotated-types==0.6.0
      - anyio==4.2.0
      - dataclasses-json==0.6.3
      - deprecated==1.2.14
      - diskcache==5.6.3
      - distro==1.9.0
      - faiss==1.7.4
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - langchain==0.1.4
      - langchain-community==0.0.16
      - langchain-core==0.1.16
      - langsmith==0.0.83
      - llama-cpp-python==0.2.33
      - llama-index==0.9.36
      - marshmallow==3.20.2
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - openai==1.9.0
      - packaging==23.2
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - sniffio==1.3.0
      - sqlalchemy==2.0.25
      - summarizer==0.0.7
      - tiktoken==0.5.2
      - typing-inspect==0.9.0
      - wrapt==1.16.0
